/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      spacing: {
        12: '48px',
      },
      lineHeight: {
        12: '48px',
        14: '56px',
      },
      borderRadius: {
        '2.5xl': '20px',
      },
      fontSize: {
        '3.5xl': '32px',
        '2.5xl': '28px',
      },
      opacity: {
        96: '0.96',
        94: '0.94',
        88: '0.88',
        64: '0.64',
        48: '0.48',
        20: '0.20',
        16: '0.16',
        12: '0.12',
        '09': '0.09',
        '08': '0.08',
        '04': '0.04',
      },
      colors: {
        primary: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
      },
      borderRadius: {
        '2.5xl': '20px',
        '4xl': '32px',
      },
    },
    fontFamily: {
      body: [
        'Inter',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      sans: [
        'Inter',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      bakbak: ['Bakbak One', 'sans-serif'],
      poppins: ['Poppins', 'sans-serif'],
      bricolage: ['Bricolage Grotesque', 'sans-serif'],
      schibsted: ['Schibsted Grotesk', 'sans-serif'],
    },
  },
  corePlugins: {
    aspectRatio: false,
  },
  plugins: [
    require('@tailwindcss/aspect-ratio'),
    require('daisyui'),
    require('@tailwindcss/typography'),
  ],
};
